### ISSUE TITLE
Remove set-quota requests from Google Sheets

### ISSUE THREAD

**Issue by LeoTomatsu** [CCI-MOC/moc-openstack-tools#88] opened 2017-10-17 16:10 UTC
Currently here's a bug on Google Sheets where processed rows are not deleted automatically.

**Comment by LeoTomatsu** [comment] 2017-10-17 16:28
Not sure exactly why yet, but this line of code is not being run [code](https://github.com/CCI-MOC/moc-openstack-tools/blob/master/set-quotas.py#L265)

**Comment by pjd-nu** [comment] 2017-10-17 16:37
First suspicion is that you're getting an exception on the line before

**Comment by xuhang57** [comment] 2017-10-17 18:03
guess you can drop a python debugger and see whether it is called?

**Comment by kamfonik** [comment] 2017-10-18 01:22
Some thoughts:
1) If you got an error from msg.send() in line 256, that can also cause copy_index to be empty and the whole if statement gets skipped.  Are the rows being appended to Processed Rows?
2) It won't delete the last non-frozen line, so if there's not a blank line at the bottom of the spreadsheet, deletion will fail (although this should result in an error from Google Sheets).

**Comment by greyspectrum** [comment] 2017-10-18 17:45
I think this is related to #92. The Google API doesn't seem to be granting write access. I'm not yet sure why that would be, since the mocwebsite .json auth file hasn't changed.

**Comment by pjd-nu** [comment] 2017-10-18 17:51
Does the auth token need to be regenerated? There were some changes to passwords and authorization recently.

**Comment by greyspectrum** [comment] 2017-10-18 17:53
@pjd-nu I'm not sure. I wasn't aware of any changes. I can ping you via email.

**Comment by greyspectrum** [comment] 2017-10-18 18:04
This is a bit of a non-sequitur, but did anyone with access to the helpdesk-vm make local changes, outside of version control? I noticed that the local is ahead of the remote today, but it was synced when I left it last.

**Comment by greyspectrum** [comment] 2017-10-18 18:10
I just checked the Google Cloud Platform API settings for the moc account. The API key there matches the one on the helpdesk-vm; it's still valid.

**Comment by kamfonik** [comment] 2017-10-19 12:06
@greyspectrum the problem with this and #92 is that the service account is only granted read access to the spreadsheet.  It needs to be granted write access.

**Comment by greyspectrum** [comment] 2017-10-19 15:00
@kamfonik Yup, the service account only had read access on both the account requests spreadsheet and the quota requests spreadsheet. This would also explain why addusers.py was running successfully from the crontab last week, but then stopped doing so. Thanks for pointing that out.

Does anyone know who changed those permissions? That totally broke the helpdesk-vm.

**Comment by greyspectrum** [comment] 2017-10-19 16:36
I've confirmed that set-quotas.py now runs successfully, from cron. My test quota request to up my instances from 10 to 20 went through successfully. I am now closing this issue.

**Closed by greyspectrum** 2017-10-19 16:36 UTC
